"""The publishing posture (NX, DESIGN §29; the one release of §39.5),
pinned keylessly: least privilege at the top of every hand-written
workflow, every action by commit SHA with its version beside it, the base
image by its index digest, the one uv pin in its four sites, Dependabot
over all four ecosystems, and the sdist declaring what never ships. The
generated release.yml is cargo-dist's (ledger #350): its permissions are
what it generates, its actions are the commits dist-workspace.toml names,
and `dist generate --check` keeps it current. A drift here would
otherwise surface only on the release that carries it."""

import re
import tomllib
from pathlib import Path
from typing import Any

import pytest
import yaml

import neosian

_ROOT = Path(__file__).resolve().parents[2]
_GENERATED = _ROOT / ".github" / "workflows" / "release.yml"
_WORKFLOWS = sorted(
    path
    for path in (_ROOT / ".github" / "workflows").glob("*.yml")
    if path != _GENERATED
)
_DOCKERFILE = _ROOT / "Dockerfile"
_PINNED_USE = re.compile(
    r"^\s*(?:-\s*)?uses:\s*\S+@[0-9a-f]{40}\s+# v\d+\.\d+\.\d+\s*$"
)
_GENERATED_USE = re.compile(r"^\s*(?:-\s*)?uses:\s*(\S+)@([0-9a-f]{40})\s*$")
_ANY_USE = re.compile(r"^\s*(?:-\s*)?uses:")
_DIGEST = re.compile(r"^FROM python:[^@\s]+@(sha256:[0-9a-f]{64})", re.M)


def _workflow(path: Path) -> dict[Any, Any]:
    # YAML 1.1 reads the `on` key as the boolean True — hence the key type.
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded


@pytest.mark.unit
@pytest.mark.parametrize("path", _WORKFLOWS, ids=lambda p: p.name)
def test_every_workflow_starts_least_privileged(path: Path) -> None:
    assert _workflow(path)["permissions"] == {"contents": "read"}


@pytest.mark.unit
@pytest.mark.parametrize("path", _WORKFLOWS, ids=lambda p: p.name)
def test_every_action_is_pinned_by_sha(path: Path) -> None:
    uses = [
        ln for ln in path.read_text(encoding="utf-8").splitlines() if _ANY_USE.match(ln)
    ]
    assert uses, f"{path.name} uses no action"
    unpinned = [ln.strip() for ln in uses if not _PINNED_USE.match(ln)]
    assert not unpinned, unpinned


@pytest.mark.unit
def test_the_generated_release_is_pinned_by_its_config() -> None:
    # cargo-dist writes release.yml from dist-workspace.toml (#350): the
    # header says so, every action is one of the commits the config names,
    # and the Python half is called as the one custom publish job.
    text = _GENERATED.read_text(encoding="utf-8")
    assert text.startswith("# This file was autogenerated by dist")
    with (_ROOT / "dist-workspace.toml").open("rb") as f:
        dist = tomllib.load(f)["dist"]
    commits = dist["github-action-commits"]
    uses = [ln for ln in text.splitlines() if _ANY_USE.match(ln)]
    for line in uses:
        if "./.github/workflows/" in line:
            assert line.strip() == "uses: ./.github/workflows/publish-python.yml"
            continue
        matched = _GENERATED_USE.match(line)
        assert matched, line
        assert commits[matched.group(1)] == matched.group(2), line
    assert dist["publish-jobs"] == ["./publish-python"]
    assert dist["publish-prereleases"] is False
    release = _workflow(_GENERATED)
    assert release["permissions"] == {"contents": "write"}
    assert release[True]["push"]["tags"]
    assert "custom-publish-python" in release["jobs"]["announce"]["needs"]


@pytest.mark.unit
def test_the_base_image_is_pinned_by_one_index_digest() -> None:
    digests = _DIGEST.findall(_DOCKERFILE.read_text(encoding="utf-8"))
    assert len(digests) == 2, "both stages pin the base image"
    assert len(set(digests)) == 1, "the two stages share one digest"


@pytest.mark.unit
def test_the_one_uv_pin_names_the_same_release_everywhere() -> None:
    # Ledger #185 widened at NX: the Dockerfile, the installer and every
    # workflow's UV_VERSION — a bump that misses one site goes red here.
    image = re.search(r"ghcr\.io/astral-sh/uv:(\d+\.\d+\.\d+)", _DOCKERFILE.read_text())
    assert image
    for path in _WORKFLOWS:
        assert _workflow(path)["env"]["UV_VERSION"] == image.group(1), path.name


@pytest.mark.unit
def test_dependabot_keeps_all_four_ecosystems() -> None:
    config = yaml.safe_load(
        (_ROOT / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    )
    ecosystems = {entry["package-ecosystem"] for entry in config["updates"]}
    assert ecosystems == {"github-actions", "uv", "docker", "cargo"}


@pytest.mark.unit
def test_the_sdist_leaves_the_planning_surface_out() -> None:
    with (_ROOT / "pyproject.toml").open("rb") as f:
        excluded = tomllib.load(f)["tool"]["hatch"]["build"]["targets"]["sdist"][
            "exclude"
        ]
    assert {
        "/docs/",
        "/record/",
        "/.claude/",
        "/.github/",
        "/.import_linter_cache/",
        "/crates/",
    } <= set(excluded)


_RELEASE = _ROOT / ".github" / "workflows" / "publish-python.yml"


@pytest.mark.unit
def test_the_release_publishes_by_trust_alone() -> None:
    # DESIGN §29: a `v*` tag publishes (through cargo-dist's release.yml,
    # which calls this workflow once the binaries are hosted, #350); a
    # dispatch rehearses; the only credential is the job's OIDC token,
    # exchanged by uv on the `pypi` environment — no long-lived secret is
    # referenced anywhere.
    text = _RELEASE.read_text(encoding="utf-8")
    release = _workflow(_RELEASE)
    build = release["jobs"]["build"]
    commands = [step.get("run", "") for step in build["steps"]]
    assert commands.index("uv audit --locked") < next(
        i for i, command in enumerate(commands) if command.startswith("uv build ")
    )
    assert release["jobs"]["pypi"]["needs"] == "build"
    assert release["jobs"]["image"]["needs"] == "build"
    triggers = release[True]
    assert triggers["workflow_call"]["inputs"]["plan"]["required"] is True
    assert "workflow_dispatch" in triggers
    assert "secrets." not in text
    pypi = release["jobs"]["pypi"]
    assert pypi["environment"]["name"] == "pypi"
    assert pypi["permissions"]["id-token"] == "write"
    publish = [
        s for s in pypi["steps"] if "--trusted-publishing always" in s.get("run", "")
    ]
    assert len(publish) == 1
    assert publish[0]["if"] == "github.event_name == 'push'"
    others = {name: job for name, job in release["jobs"].items() if name != "pypi"}
    assert not any("id-token" in job.get("permissions", {}) for job in others.values())


@pytest.mark.unit
def test_the_changelog_names_the_version() -> None:
    # Keep a Changelog, kept by the gate (DESIGN §29): `[Unreleased]`
    # accumulates during a phase, the close names the version, and a bump
    # without its section goes red here before `make release` refuses it.
    text = (_ROOT / "docs" / "CHANGELOG.md").read_text(encoding="utf-8")
    assert "\n## [Unreleased]\n" in text
    assert f"\n## [{neosian.__version__}] - " in text
    assert f"[{neosian.__version__}]: https://github.com/mausa-ai/neosian/" in text
